export const assignment = [
  {
    id: 1,
    title: 'Essay on Shakespeare',
    point: 100,
    duedate: '2023-06-15',
    type: 'essay',
  },
  {
    id: 2,
    title: 'Multiple Choice Quiz on History',
    point: 50,
    duedate: '2023-06-20',
    type: 'multiple choice',
  },
  {
    id: 3,
    title: 'Presentation on Global Warming',
    point: 75,
    duedate: '2023-06-25',
    type: 'presentation',
  },
  {
    id: 4,
    title: 'Essay on Psychology',
    point: 90,
    duedate: '2023-06-28',
    type: 'essay',
  },
  {
    id: 5,
    title: 'Multiple Choice Quiz on Math',
    point: 70,
    duedate: '2023-07-02',
    type: 'multiple choice',
  },
  {
    id: 6,
    title: 'Presentation on Literature',
    point: 80,
    duedate: '2023-07-06',
    type: 'presentation',
  },
  {
    id: 7,
    title: 'Essay on Science',
    point: 95,
    duedate: '2023-07-10',
    type: 'essay',
  },
  {
    id: 8,
    title: 'Multiple Choice Quiz on English',
    point: 60,
    duedate: '2023-07-14',
    type: 'multiple choice',
  },
  {
    id: 9,
    title: 'Presentation on History',
    point: 85,
    duedate: '2023-07-18',
    type: 'presentation',
  },
  {
    id: 10,
    title: 'Essay on Politics',
    point: 80,
    duedate: '2023-07-22',
    type: 'essay',
  },
  {
    id: 11,
    title: 'Multiple Choice Quiz on Science',
    point: 65,
    duedate: '2023-07-26',
    type: 'multiple choice',
  },
  {
    id: 12,
    title: 'Presentation on Economics',
    point: 90,
    duedate: '2023-07-30',
    type: 'presentation',
  },
  {
    id: 13,
    title: 'Essay on Art',
    point: 85,
    duedate: '2023-08-03',
    type: 'essay',
  },
  {
    id: 14,
    title: 'Multiple Choice Quiz on Geography',
    point: 55,
    duedate: '2023-08-07',
    type: 'multiple choice',
  },
  {
    id: 15,
    title: 'Presentation on Politics',
    point: 75,
    duedate: '2023-08-11',
    type: 'presentation',
  },
];
