export const cities = [
  { id: 1, name: 'Port Blair', state_id: 1 },
  { id: 2, name: 'Adoni', state_id: 2 },
  { id: 3, name: 'Amaravati', state_id: 2 },
  { id: 4, name: 'Anantapur', state_id: 2 },
  { id: 5, name: 'Bhimavaram', state_id: 2 },
  { id: 6, name: 'Chittoor', state_id: 2 },
  { id: 7, name: 'Dharmavaram', state_id: 2 },
  { id: 8, name: 'Eluru', state_id: 2 },
  { id: 9, name: 'Gudivada', state_id: 2 },
  { id: 10, name: 'Guntakal', state_id: 2 },
  { id: 11, name: 'Guntur', state_id: 2 },
  { id: 12, name: 'Hindupur', state_id: 2 },
  { id: 13, name: 'Kadapa', state_id: 2 },
  { id: 14, name: 'Kakinada', state_id: 2 },
  { id: 15, name: 'Kavali', state_id: 2 },
  { id: 16, name: 'Kurnool', state_id: 2 },
  { id: 17, name: 'Machilipatnam', state_id: 2 },
  { id: 18, name: 'Madanapalle', state_id: 2 },
  { id: 19, name: 'Nandyal', state_id: 2 },
  { id: 20, name: 'Narasaraopet', state_id: 2 },
  { id: 21, name: 'Nellore', state_id: 2 },
  { id: 22, name: 'Ongole', state_id: 2 },
  { id: 23, name: 'Rajahmundry', state_id: 2 },
  { id: 24, name: 'Srikakulam', state_id: 2 },
  { id: 25, name: 'Tadepalligudem', state_id: 2 },
  { id: 26, name: 'Tadipatri', state_id: 2 },
  { id: 27, name: 'Tenali', state_id: 2 },
  { id: 28, name: 'Vijayanagaram', state_id: 2 },
  { id: 29, name: 'Vijayawada', state_id: 2 },
  { id: 30, name: 'Visakhapatnam', state_id: 2 },
  { id: 31, name: 'Bongaigaon', state_id: 2 }
];
