export const cities = [
  { id: 1, name: 'Alipur', stateId: 1 },
  { id: 2, name: 'Andaman Island', stateId: 1 },
  { id: 3, name: 'Anderson Island', stateId: 1 },
  { id: 4, name: 'Arainj-Laka-Punga', stateId: 1 },
  { id: 5, name: 'Austinabad', stateId: 1 },
  { id: 6, name: 'Bamboo Flat', stateId: 1 },
  { id: 7, name: 'Barren Island', stateId: 1 },
  { id: 8, name: 'Beadonabad', stateId: 1 },
  { id: 9, name: 'Betapur', stateId: 1 },
  { id: 10, name: 'Bindraban', stateId: 1 },
  { id: 11, name: 'Bonington', stateId: 1 },
  { id: 12, name: 'Brookesabad', stateId: 1 },
  { id: 13, name: 'Cadell Point', stateId: 1 },
  { id: 14, name: 'Calicut', stateId: 1 },
  { id: 15, name: 'Chetamale', stateId: 1 },
  { id: 16, name: 'Cinque Islands', stateId: 1 },
  { id: 17, name: 'Defence Island', stateId: 1 },
  { id: 18, name: 'Digilpur', stateId: 1 },
  { id: 19, name: 'Dolyganj', stateId: 1 },
  { id: 20, name: 'Flat Island', stateId: 1 },
  { id: 21, name: 'Geinyale', stateId: 1 },
  { id: 22, name: 'Great Coco Island', stateId: 1 },
  { id: 23, name: 'Haddo', stateId: 1 },
  { id: 24, name: 'Havelock Island', stateId: 1 },
  { id: 25, name: 'Henry Lawrence Island', stateId: 1 },
  { id: 26, name: 'Herbertabad', stateId: 1 },
  { id: 27, name: 'Hobdaypur', stateId: 1 },
  { id: 28, name: 'Ilichar', stateId: 1 },
  { id: 29, name: 'Ingoie', stateId: 1 },
  { id: 30, name: 'Inteview Island', stateId: 1 },
  { id: 31, name: 'Jangli Ghat', stateId: 1 },
  { id: 32, name: 'Jhon Lawrence Island', stateId: 1 },
  { id: 33, name: 'Karen', stateId: 1 },
  { id: 34, name: 'Kartara', stateId: 1 },
  { id: 35, name: 'KYD Islannd', stateId: 1 },
  { id: 36, name: 'Landfall Island', stateId: 1 },
];
