export const CoursesSelectData = [
  { id: 1, name: 'JEE Main' },
  { id: 2, name: 'JEE Advanced' },
  { id: 3, name: 'NEET' },
  { id: 4, name: 'UPSC Civil Services' },
  { id: 5, name: 'CAT' },
  { id: 6, name: 'GATE' },
  { id: 7, name: 'SSC' },
  { id: 8, name: 'IBPS' },
  { id: 9, name: 'CLAT' },
  { id: 10, name: 'NDA' },
  { id: 11, name: 'AIIMS' },
  { id: 12, name: 'UGC NET' },
  { id: 13, name: 'CSIR NET' },
  { id: 14, name: 'CTET' },
  { id: 15, name: 'IAS' },
  { id: 16, name: 'IPS' },
  { id: 17, name: 'IFS' },
  { id: 18, name: 'Bank PO' },
  { id: 19, name: 'Bank Clerk' },
  { id: 20, name: 'CDS' },
];
