export const courses = [
  {
    name: 'Introduction to Programming',
    duration: '6 weeks',
    level: 'Beginner',
    category: 'Computer Science',
    instructor: 'John Smith',
    format: 'Online',
    fee: 99.99,
  },
  {
    name: 'Web Development Fundamentals',
    duration: '8 weeks',
    level: 'Intermediate',
    category: 'Web Development',
    instructor: 'Jane Doe',
    format: 'In-person',
    fee: 299.99,
  },
  {
    name: 'Mobile App Development',
    duration: '12 weeks',
    level: 'Advanced',
    category: 'Mobile Development',
    instructor: 'Bob Johnson',
    format: 'Online',
    fee: 499.99,
  },
  {
    name: 'Data Science Essentials',
    duration: '10 weeks',
    level: 'Intermediate',
    category: 'Data Science',
    instructor: 'Alice Kim',
    format: 'In-person',
    fee: 399.99,
  },
  {
    name: 'Artificial Intelligence',
    duration: '14 weeks',
    level: 'Advanced',
    category: 'Computer Science',
    instructor: 'Tom Lee',
    format: 'Online',
    fee: 599.99,
  },
  {
    name: 'Business Analytics',
    duration: '8 weeks',
    level: 'Intermediate',
    category: 'Business',
    instructor: 'Samantha Brown',
    format: 'In-person',
    fee: 299.99,
  },
  {
    name: 'Graphic Design Principles',
    duration: '6 weeks',
    level: 'Beginner',
    category: 'Design',
    instructor: 'David Chen',
    format: 'Online',
    fee: 99.99,
  },
  {
    name: 'Photography Basics',
    duration: '4 weeks',
    level: 'Beginner',
    category: 'Photography',
    instructor: 'Lisa Wang',
    format: 'In-person',
    fee: 199.99,
  },
  {
    name: 'Marketing Strategies',
    duration: '12 weeks',
    level: 'Advanced',
    category: 'Marketing',
    instructor: 'Erica Johnson',
    format: 'Online',
    fee: 499.99,
  },
  {
    name: 'Public Speaking Mastery',
    duration: '8 weeks',
    level: 'Intermediate',
    category: 'Communication',
    instructor: 'Steve Davis',
    format: 'In-person',
    fee: 299.99,
  },
  {
    name: 'Leadership Development',
    duration: '10 weeks',
    level: 'Advanced',
    category: 'Business',
    instructor: 'Chris Lee',
    format: 'Online',
    fee: 599.99,
  },
  {
    name: 'Project Management Essentials',
    duration: '6 weeks',
    level: 'Beginner',
    category: 'Business',
    instructor: 'Anna Kim',
    format: 'In-person',
    fee: 199.99,
  },
  {
    name: 'English Writing Skills',
    duration: '8 weeks',
    level: 'Intermediate',
    category: 'Language',
    instructor: 'Maria Hernandez',
    format: 'Online',
    fee: 299.99,
  },
  {
    name: 'French Language Basics',
    duration: '10 weeks',
    level: 'Beginner',
    category: 'Language',
    instructor: 'Claire Dupont',
    format: 'In-person',
    fee: 199.99,
  },
  {
    name: 'Spanish Language Basics',
    duration: '10 weeks',
    level: 'Beginner',
    category: 'Language',
    instructor: 'Carlos Sanchez',
    format: 'In-person',
    fee: 199.99,
  },
  {
    name: 'German Language Basics',
    duration: '10 weeks',
    level: 'Beginner',
    category: 'Language',
    instructor: 'Hans Muller',
    format: 'In-person',
    fee: 199.99,
  },
  {
    name: 'Chinese Language Basics',
    duration: '10 weeks',
    level: 'Beginner',
    category: 'Language',
    instructor: 'Li Wei',
    format: 'In-person',
    fee: 199.99,
  },
  {
    name: 'Digital Marketing',
    duration: '12 weeks',
    level: 'Intermediate',
    category: 'Marketing',
    instructor: 'Mike Johnson',
    format: 'Online',
    fee: 499.99,
  },
  {
    name: 'Art History',
    duration: '6 weeks',
    level: 'Beginner',
    category: 'Art',
    instructor: 'Emily Davis',
    format: 'In-person',
    fee: 99.99,
  },
  {
    name: 'Music Theory',
    duration: '8 weeks',
    level: 'Beginner',
    category: 'Music',
    instructor: 'Daniel Kim',
    format: 'Online',
    fee: 299.99,
  },
];
