export const courses = [
  {
    id: 1,
    name: 'JEE Main',
    duration: '1 year',
    level: 'Undergraduate',
    category: 'Engineering',
    instructor: 'Dr. Rajesh Sharma',
    format: 'Online and offline',
    fee: 150000,
  },
  {
    id: 2,
    name: 'NEET',
    duration: '1 year',
    level: 'Undergraduate',
    category: 'Medical',
    instructor: 'Prof. Swati Gupta',
    format: 'Online and offline',
    fee: 200000,
  },
  {
    id: 3,
    name: 'UGC NET',
    duration: '6-12 months',
    level: 'Postgraduate',
    category: 'Teaching and Research',
    instructor: 'Dr. Amit Singh',
    format: 'Online and offline',
    fee: 80000,
  },
  {
    id: 4,
    name: 'CSIR NET',
    duration: '6-12 months',
    level: 'Postgraduate',
    category: 'Teaching and Research',
    instructor: 'Ms. Neha Verma',
    format: 'Online and offline',
    fee: 100000,
  },
  {
    id: 5,
    name: 'CTET',
    duration: '6 months',
    level: 'Undergraduate',
    category: 'Teaching',
    instructor: 'Dr. Rajesh Sharma',
    format: 'Online and offline',
    fee: 50000,
  },
  {
    id: 6,
    name: 'IAS',
    duration: '1-2 years',
    level: 'Graduate',
    category: 'Civil Services',
    instructor: 'Mr. Amit Singh',
    format: 'Online and offline',
    fee: 300000,
  },
  {
    id: 7,
    name: 'IPS',
    duration: '1-2 years',
    level: 'Graduate',
    category: 'Civil Services',
    instructor: 'Mr. Amit Singh',
    format: 'Online and offline',
    fee: 300000,
  },
  {
    id: 8,
    name: 'IFS',
    duration: '1-2 years',
    level: 'Graduate',
    category: 'Civil Services',
    instructor: 'Mr. Amit Singh',
    format: 'Online and offline',
    fee: 300000,
  },
  {
    id: 9,
    name: 'Bank PO',
    duration: '6-12 months',
    level: 'Undergraduate',
    category: 'Banking',
    instructor: 'Prof. Swati Gupta',
    format: 'Online and offline',
    fee: 80000,
  },
  {
    id: 10,
    name: 'Bank Clerk',
    duration: '6-12 months',
    level: 'Undergraduate',
    category: 'Banking',
    instructor: 'Prof. Swati Gupta',
    format: 'Online and offline',
    fee: 50000,
  },
  {
    id: 11,
    name: 'CDS',
    duration: '6-12 months',
    level: 'Undergraduate',
    category: 'Defence',
    instructor: 'Dr. Rajesh Sharma',
    format: 'Offline',
    fee: 150000,
  },
];
