export const instructors = [
  { id: 1, firstName: 'Ravi', lastName: 'Sharma' },
  { id: 2, firstName: 'Priya', lastName: 'Patel' },
  { id: 3, firstName: 'Rajesh', lastName: 'Gupta' },
  { id: 4, firstName: 'Naina', lastName: 'Khanna' },
  { id: 5, firstName: 'Sanjay', lastName: 'Verma' },
  { id: 6, firstName: 'Meera', lastName: 'Joshi' },
  { id: 7, firstName: 'Deepak', lastName: 'Singhania' },
  { id: 8, firstName: 'Aarti', lastName: 'Desai' },
  { id: 9, firstName: 'Rohit', lastName: 'Malhotra' },
  { id: 10, firstName: 'Shalini', lastName: 'Chatterjee' },
  { id: 11, firstName: 'Anand', lastName: 'Kapoor' },
  { id: 12, firstName: 'Pooja', lastName: 'Agrawal' },
  { id: 13, firstName: 'Ajay', lastName: 'Bhatia' },
  { id: 14, firstName: 'Nisha', lastName: 'Reddy' },
  { id: 15, firstName: 'Vikram', lastName: 'Mehra' },
  { id: 16, firstName: 'Neha', lastName: 'Sharma' },
  { id: 17, firstName: 'Sameer', lastName: 'Rao' },
  { id: 18, firstName: 'Shweta', lastName: 'Kapoor' },
  { id: 19, firstName: 'Rahul', lastName: 'Choudhary' },
  { id: 20, firstName: 'Sonali', lastName: 'Banerjee' },
];
