export const users = [
  {
    id: 1,
    name: 'Kalyani_priya',
    username: 'kalyani_priya',
    email: 'kalyani@example.com',
    role: 'teacher',
    joiningDate: '01-01-2021',
    color: '#f0e6d2',
  },
  {
    id: 2,
    name: 'Swati Gupta',
    username: 'swati_gupta',
    email: 'swati_gupta@example.com',
    role: 'teacher',
    joiningDate: '01-02-2021',
    color: '#f6e9d9',
  },
  {
    id: 3,
    name: 'Amit Singh',
    username: 'amit_singh',
    email: 'amit_singh@example.com',
    role: 'teacher',
    joiningDate: '01-03-2021',
    color: '#e9f6d9',
  },
  {
    id: 4,
    name: 'Neha Verma',
    username: 'neha_verma',
    email: 'neha_verma@example.com',
    role: 'teacher',
    joiningDate: '01-04-2021',
    color: '#d9e9f6',
  },
  {
    id: 5,
    name: 'Suresh Kumar',
    username: 'suresh_kumar',
    email: 'suresh_kumar@example.com',
    role: 'student',
    joiningDate: '01-05-2021',
    color: '#f0e6d2',
  },
  {
    id: 6,
    name: 'Priya Singh',
    username: 'priya_singh',
    email: 'priya_singh@example.com',
    role: 'student',
    joiningDate: '01-06-2021',
    color: '#f6e9d9',
  },
  {
    id: 7,
    name: 'Rahul Verma',
    username: 'rahul_verma',
    email: 'rahul_verma@example.com',
    role: 'student',
    joiningDate: '01-07-2021',
    color: '#e9f6d9',
  },
  {
    id: 8,
    name: 'Mohit Sharma',
    username: 'mohit_sharma',
    email: 'mohit_sharma@example.com',
    role: 'student',
    joiningDate: '01-08-2021',
    color: '#d9e9f6',
  },
  {
    id: 9,
    name: 'Anjali Yadav',
    username: 'anjali_yadav',
    email: 'anjali_yadav@example.com',
    role: 'student',
    joiningDate: '01-09-2021',
    color: '#f0e6d2',
  },
  {
    id: 10,
    name: 'Akash Patel',
    username: 'akash_patel',
    email: 'akash_patel@example.com',
    role: 'student',
    joiningDate: '01-10-2021',
    color: '#f6e9d9',
  },
  {
    id: 11,
    name: 'Anjali Sharma',
    username: 'anjali_01',
    email: 'anjali.sharma@example.com',
    role: 'teacher',
    joiningDate: '01-01-2021',
    color: '#F7CAC9',
  },
  {
    id: 12,
    name: 'Rohit Kumar',
    username: 'rohit_02',
    email: 'rohit.kumar@example.com',
    role: 'student',
    joiningDate: '01-02-2021',
    color: '#F7DC6F',
  },
  {
    id: 13,
    name: 'Sujata Singh',
    username: 'sujata_03',
    email: 'sujata.singh@example.com',
    role: 'student',
    joiningDate: '02-03-2021',
    color: '#D5F5E3',
  },
  {
    id: 14,
    name: 'Gaurav Sharma',
    username: 'gaurav_04',
    email: 'gaurav.sharma@example.com',
    role: 'teacher',
    joiningDate: '02-04-2021',
    color: '#F9E79F',
  },
  {
    id: 15,
    name: 'Amit Patel',
    username: 'amit_05',
    email: 'amit.patel@example.com',
    role: 'student',
    joiningDate: '03-05-2021',
    color: '#FADBD8',
  },
  {
    id: 16,
    name: 'Neha Gupta',
    username: 'neha_06',
    email: 'neha.gupta@example.com',
    role: 'student',
    joiningDate: '03-06-2021',
    color: '#D6DBDF',
  },
  {
    id: 17,
    name: 'Shubham Singh',
    username: 'shubham_07',
    email: 'shubham.singh@example.com',
    role: 'teacher',
    joiningDate: '04-07-2021',
    color: '#D7BDE2',
  },
  {
    id: 18,
    name: 'Tanvi Shah',
    username: 'tanvi_08',
    email: 'tanvi.shah@example.com',
    role: 'student',
    joiningDate: '04-08-2021',
    color: '#A3E4D7',
  },
  {
    id: 19,
    name: 'Rajiv Desai',
    username: 'rajiv_09',
    email: 'rajiv.desai@example.com',
    role: 'teacher',
    joiningDate: '05-09-2021',
    color: '#EDBB99',
  },
  {
    id: 20,
    name: 'Aarti Gupta',
    username: 'aarti_10',
    email: 'aarti.gupta@example.com',
    role: 'student',
    joiningDate: '05-10-2021',
    color: '#ABEBC6',
  },
  {
    id: 21,
    name: 'Karan Patel',
    username: 'karan_11',
    email: 'karan.patel@example.com',
    role: 'student',
    joiningDate: '06-11-2021',
    color: '#F5B7B1',
  },
];
